dbt_project_repos:
  outputs:
    dev:
      account: eayvwia-eq21282
      database: RAW
      password: Tanvireddy2112$
      role: accountadmin
      schema: staging
      threads: 1
      type: snowflake
      user: consultant1028
      warehouse: compute_wh
  target: dev

